/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2018-12-18 06:46:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blogpost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Multikeyword</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Bike Race Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\"/>\r\n");
      out.write("<!-- fonts -->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Michroma\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Comfortaa:300,400,700\" rel=\"stylesheet\">\r\n");
      out.write("<!-- /fonts -->\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href='css/aos.css' rel='stylesheet prefetch' type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- /css -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- navigation -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\" data-aos=\"flip-up\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\"><h1>Multikeyword</h1></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav slide-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active current\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Data Owner <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"dataownerregistration.jsp\">Registration</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"dataownerlogin.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Administrator <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"administratorlogin.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Cloud  <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"cloudserverlogin.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">User <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"userregistration.jsp\">Registration</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"userlogin.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\t\t\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- /navigation --> \r\n");
      out.write("<!-- Page Content -->\r\n");
      out.write("<!-- header section -->\r\n");
      out.write("<section class=\"inner-w3ls\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\t\t<h3 class=\"text-center\" data-aos=\"zoom-in\">Multikeyword</h3>\r\n");
      out.write("        <!-- Page Heading/Breadcrumbs -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <ol class=\"breadcrumb\" data-aos=\"zoom-in\">\r\n");
      out.write("                    <li><a href=\"index.jsp\">Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"active\">Multikeyword Modules</li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\t\r\n");
      out.write("<!-- /header section -->\r\n");
      out.write("<section class=\"blogpost-w3layouts\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<! -- SINGLE POST -->\r\n");
      out.write("\t\t<div class=\"col-lg-8\" data-aos=\"flip-left\">\r\n");
      out.write("\t\t\t<! -- Blog Post 1 -->\r\n");
      out.write("\t\t\t<p class=\"blogpost-p1\">\r\n");
      out.write("\t\t\t\t<div class=\"hover01 column\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<figure><img class=\"img-responsive\" src=\"images/blogpost.jpg\" data-aos=\"zoom-in\"></figure>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<a href=\"blogpost.html\" class=\"blogpost-w3ls\" data-aos=\"flip-up\"><h3>Admin</h3></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p class=\"blogpost-p3\" data-aos=\"flip-up\">A person responsible for the performance or management of administrative business operations.\r\n");
      out.write("            <b>Cloud administrators have two primary responsibilities:</b> Configure the Cloud Management service and monitor and manage the services.\r\n");
      out.write("\t\t\tAdmin login to system and upload file .Admin can view all file details. He gets the request from user for secrete key and send the secrete key to users mail.</p>\r\n");
      out.write("\t\t\t<div class=\"hline\"></div>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t<!-- Blog Comments -->\r\n");
      out.write("\t\t\t<div class=\"hline\"></div>\r\n");
      out.write("\t\t\t<!-- Comments Form -->\r\n");
      out.write("\t\t\t<a href=\"blogpost.html\" class=\"blogpost-w3ls\" data-aos=\"flip-up\"><h3>Trustee</h3></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p class=\"blogpost-p3\" data-aos=\"flip-up\">Access to customer data is under the control of the data trustee.Trustee login to system and accept the user request for his entry in system.</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"hline\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a href=\"blogpost.html\" class=\"blogpost-w3ls\" data-aos=\"flip-up\"><h3>Cloud Server</h3></a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<p class=\"blogpost-p3\" data-aos=\"flip-up\">A cloud server is a logical server that is built, hosted and delivered through a cloud computing platform over the Internet. Cloud servers possess and exhibit similar capabilities and functionality to a typical server but are accessed remotely from a cloud service provider.\r\n");
      out.write("\r\n");
      out.write("A cloud server may also be called a virtual server or virtual private sever  We can store any data on a cloud server.user can download  file from cloud server.</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"hline\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a href=\"blogpost.html\" class=\"blogpost-w3ls\" data-aos=\"flip-up\"><h3>User</h3></a>\r\n");
      out.write("\t\t<p class=\"blogpost-p3\" data-aos=\"flip-up\">User register to the system with scanning finger print and send the request to activate him. User login to system with first time by OTP   and gives scanned image if they matched user   logged in to system. User view files and send request for secrete key to admin. When users get secrete key user can download the file by entering secrete key. If secrete key lost then user can   again request for key.</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"hline\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("           \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t \t<! -- SIDEBAR -->\r\n");
      out.write("\t\t\r\n");
      out.write("<section class=\"last-w3layouts\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<a href=\"index.html\" class=\"bottom-agile\"><h2 class=\"text-center\">Multikeyword</h2></a>\r\n");
      out.write("\t\t<p class=\"text-center\">Privacy Preserving Ranked Multi-Keyword\r\n");
      out.write("Search for Multiple Data Owners in\r\n");
      out.write("Cloud Computing </p>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</section>\r\n");
      out.write("<!-- last section -->\t\r\n");
      out.write("<!-- back to top -->\r\n");
      out.write("<a href=\"#0\" class=\"cd-top\">Top</a>\r\n");
      out.write("<!-- /back to top -->\r\n");
      out.write("<!-- js files -->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/SmoothScroll.min.js\"></script>\r\n");
      out.write("<script src=\"js/top.js\"></script> \r\n");
      out.write("<script src=\"js/modernizr.min.js\"></script>\r\n");
      out.write("<script src=\"js/index.js\"></script>\r\n");
      out.write("<script src='js/aos.js'></script>\r\n");
      out.write("<script src=\"js/aos2.js\"></script>\r\n");
      out.write("<!-- /js files -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
