/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2018-12-14 17:47:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dataownerregistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"keywords\" content=\"Validation Signup Form Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- fonts -->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Muli:300,400\" rel=\"stylesheet\">\r\n");
      out.write("<!-- /fonts -->\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link href=\"registration/css/bootstrap.css\" rel=\"stylesheet\" type='text/css' media=\"all\" />\r\n");
      out.write("<link href=\"registration/css/style.css\" rel=\"stylesheet\" type='text/css' media=\"all\" />\r\n");
      out.write("<!-- /css -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1 class=\"w3ls\">Sign Up</h1>\r\n");
      out.write("\t<div class=\"content-agileits\">\r\n");
      out.write("\t\t<form action=\"DataOwnerLogin\" method=\"post\" data-toggle=\"validator\" role=\"form\">\r\n");
      out.write("\t\t\t<div class=\"form-group w3layouts w3 w3l\">\r\n");
      out.write("\t\t\t\t<label for=\"firstname\" class=\"control-label\">Name</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"name\" pattern =\"[A-Z][a-z]+\" class=\"form-control\"  id=\"name\" placeholder=\"Name\" data-error=\"Enter Valid First Name\" required>\r\n");
      out.write("\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group w3l agileinfo wthree w3-agileits\">\r\n");
      out.write("\t\t\t\t<label for=\"inputEmail\" class=\"control-label\">Email</label>\r\n");
      out.write("\t\t\t\t<input type=\"email\" name=\"email\"  pattern=\"[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,3}$\" class=\"form-control\"  id=\"email\" placeholder=\"Email\" data-error=\"This email address is invalid\" required>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group agileinfo wthree w3-agileits agile\">\r\n");
      out.write("\t\t\t\t<label for=\"Phone\" class=\"control-label\">Phone</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name= \"contact\" pattern=\"[789][0-9]{9}\"id=\"Phone\" placeholder=\"Phone\" data-error=\"Enter Your Phone Number\" required>\r\n");
      out.write("\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\t<div class=\"form-group agile agileits-w3layouts w3-agile\">\r\n");
      out.write("\t\t\t\t<label for=\"inputPassword\" class=\"control-label\">Password</label>\r\n");
      out.write("\t\t\t\t<div class=\"form-inline row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-6 agileits-w3layouts\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\"  name=\"password\" pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}\"  data-minlength=\"6\" class=\"form-control\" id=\"inputPassword\" placeholder=\"Password\" required>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"help-block\">Enter Valid Pattern</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-6 w3-agile\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\"  name=\"confirmpassword\" pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}\"  class=\"form-control\" id=\"inputPasswordConfirm\" data-match=\"#inputPassword\" data-match-error=\"Whoops, these don't match\" placeholder=\"Confirm Password\" required>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"help-block with-errors\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t          \r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-lg\" name=\"submit\" value=\"SignUp\" >Sign IN </button> <br>\r\n");
      out.write("\t\t\t<center>\t<a href=\"userlogin.jsp\">Login</a> </center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<center><a href=\"index.jsp\">Back To Home</a></center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("    </div>\r\n");
      out.write("<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t<p>Attack prevention and detection using Access Control Encrypted Cloud Storage</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- js files -->\r\n");
      out.write("<script src=\"registration/js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<script src=\"registration/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"registration/js/validator.min.js\"></script>\r\n");
      out.write("<!-- /js files -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
