/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2018-12-13 08:32:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Attacker System</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Bike Race Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<!-- fonts -->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Michroma\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Comfortaa:300,400,700\" rel=\"stylesheet\">\r\n");
      out.write("<!-- /fonts -->\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href='css/aos.css' rel='stylesheet prefetch' type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/jquery.mb.thumbgallery.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/info.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/banner.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- /css -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- navigation -->\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\" data-aos=\"flip-up\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\"><h1>Attacker System</h1></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav slide-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active current\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Data Owner <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"dataownerregistration.jsp\">Registration</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"dataownerlogin.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Cloud  <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"cloudserverlogin.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">User <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"userregistration.jsp\">Registration</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"userlogin.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\t\t\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- /navigation -->\r\n");
      out.write("<!-- banner section -->\r\n");
      out.write("<div class=\"demo-2\">\r\n");
      out.write("\t<div id=\"slider\" class=\"sl-slider-wrapper\">\r\n");
      out.write("\t\t<div class=\"sl-slider\">\r\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"horizontal\" data-slice1-rotation=\"-25\" data-slice2-rotation=\"-25\" data-slice1-scale=\"2\" data-slice2-scale=\"2\">\r\n");
      out.write("\t\t\t\t<div class=\"sl-slide-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-img bg-img-1\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"vertical\" data-slice1-rotation=\"10\" data-slice2-rotation=\"-15\" data-slice1-scale=\"1.5\" data-slice2-scale=\"1.5\">\r\n");
      out.write("\t\t\t\t<div class=\"sl-slide-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-img bg-img-2\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"horizontal\" data-slice1-rotation=\"3\" data-slice2-rotation=\"3\" data-slice1-scale=\"2\" data-slice2-scale=\"1\">\r\n");
      out.write("\t\t\t\t<div class=\"sl-slide-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-img bg-img-3\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"vertical\" data-slice1-rotation=\"-5\" data-slice2-rotation=\"25\" data-slice1-scale=\"2\" data-slice2-scale=\"1\">\r\n");
      out.write("\t\t\t\t<div class=\"sl-slide-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-img bg-img-4\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"horizontal\" data-slice1-rotation=\"-5\" data-slice2-rotation=\"10\" data-slice1-scale=\"2\" data-slice2-scale=\"1\">\r\n");
      out.write("\t\t\t\t<div class=\"sl-slide-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-img bg-img-5\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div><!-- /sl-slider -->\r\n");
      out.write("\t\t<nav id=\"nav-dots\" class=\"nav-dots\">\r\n");
      out.write("\t\t\t<span class=\"nav-dot-current\"></span>\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t\t<span></span>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div><!-- /slider-wrapper -->\r\n");
      out.write("</div>\t\r\n");
      out.write("<!-- /banner section -->\r\n");
      out.write("<!-- info section -->\r\n");
      out.write("<section class=\"info-w3ls\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"col-lg-6 col-md-6 info-wthree\">\r\n");
      out.write("\t\t\t<div class=\"info-agile1\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-5 info-w3layouts1\" data-aos=\"flip-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ch-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ch-item\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ch-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ch-info-front ch-img-1\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ch-info-back1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 >Data Owner</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Attacker System</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-7 info-w3layouts2\" data-aos=\"flip-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info-agileits\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Data Owner</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Data ownerlogin to system and upload file with a different senerios .Data owner can view all file details.  </p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-hand-o-right\" aria-hidden=\"true\"></i> Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-lg-6 col-md-6 info-wthree\">\r\n");
      out.write("\t\t\t<div class=\"info-agile1\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-5 info-w3layouts1\" data-aos=\"flip-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ch-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ch-item\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ch-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ch-info-front ch-img-3\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ch-info-back3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Cloud Server</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Attacker System</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-7 info-w3layouts2\" data-aos=\"flip-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info-agileits\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Cloud Server</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Information are store on a cloud server.Users,Data Owners and files are stored on cloud. </p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-hand-o-right\" aria-hidden=\"true\"></i> Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-lg-6 col-md-6 info-wthree\">\r\n");
      out.write("\t\t\t<div class=\"info-agile2\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-5 info-w3layouts1\" data-aos=\"flip-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ch-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ch-item\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ch-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ch-info-front ch-img-4\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ch-info-back4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>User</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Attacker System</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-7 info-w3layouts2\" data-aos=\"flip-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info-agileits\">\r\n");
      out.write("\t\t\t\t\t\t<h4>User</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>User register to the system.Search the query</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-hand-o-right\" aria-hidden=\"true\"></i> Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- /info section -->\r\n");
      out.write("\r\n");
      out.write("<!-- recent pics section -->\r\n");
      out.write("\r\n");
      out.write("<!-- /recent pics section -->\r\n");
      out.write("<!-- last section -->\r\n");
      out.write("<section class=\"last-w3layouts\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<a href=\"index.html\" class=\"bottom-agile\"><h2 class=\"text-center\">Attacker System</h2></a>\r\n");
      out.write("\t\t<div class=\"copyright\">\r\n");
      out.write("<p>Attack prevention and detection using Access Control Encrypted Cloud Storage.\t </p>\r\n");
      out.write("</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</section>\r\n");
      out.write("<!-- last section -->\r\n");
      out.write("<!-- back to top -->\r\n");
      out.write("<a href=\"#0\" class=\"cd-top\">Top</a>\r\n");
      out.write("<!-- /back to top -->\r\n");
      out.write("<!-- js files -->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/SmoothScroll.min.js\"></script>\r\n");
      out.write("<script src=\"js/top.js\"></script> \r\n");
      out.write("<script src=\"js/modernizr.min.js\"></script>\r\n");
      out.write("<script src=\"js/index.js\"></script>\r\n");
      out.write("<script src=\"js/jarallax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    /* init Jarallax */\r\n");
      out.write("\t$('.jarallax').jarallax({\r\n");
      out.write("        speed: 0.6,\r\n");
      out.write("        imgWidth: 1366,\r\n");
      out.write("        imgHeight: 768\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("<script src='js/aos.js'></script>\r\n");
      out.write("<script src=\"js/aos2.js\"></script>\r\n");
      out.write("<!-- js for recent pics section -->\r\n");
      out.write("<script src=\"js/jquery.mb.thumbGallery.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    var isIframe = function() {\r\n");
      out.write("        var a = !1;\r\n");
      out.write("        try {\r\n");
      out.write("            self.location.href != top.location.href && ( a = !0 )\r\n");
      out.write("        } catch ( b ) {\r\n");
      out.write("            a = !0\r\n");
      out.write("        }\r\n");
      out.write("        return a\r\n");
      out.write("    };\r\n");
      out.write("    if ( !isIframe() ) {\r\n");
      out.write("        var logo = $( \"<a href='#' style='position:absolute;top:0;z-index:1000'><img id='logo' border='0' src='#' alt='mb.ideas.repository'></a>\" );\r\n");
      out.write("        $( \"#wrapper\" ).prepend( logo ), $( \"#logo\" ).fadeIn()\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Extend or modify effects */\r\n");
      out.write("    jQuery.thumbGrid.transitions.fadeIn = {in: {x:\"0\", opacity:0, scale:0.9}, out: {x:0, opacity:0}};\r\n");
      out.write("    jQuery.thumbGrid.transitions.fadeOut = {in: {x:\"0\", opacity:0}, out: {x:0, scale:0.9, opacity:0}};\r\n");
      out.write("    jQuery.thumbGrid.transitions.slideLeft = {in: {x:$(window).width(), opacity:0}, out: {x:-$(window).width(), opacity:0}, ease:\"cubic-bezier(.43,.18,.81,1.07)\"};\r\n");
      out.write("    jQuery.thumbGrid.transitions.slideRight = {in: {x:0, opacity:0}, out: {x:$(window).width(), opacity:0}, ease:\"cubic-bezier(.43,.18,.81,1.07)\"};\r\n");
      out.write("\r\n");
      out.write("    /* Initialize the gallery */\r\n");
      out.write("    jQuery(\"#thumbGrid\").thumbGrid();\r\n");
      out.write("\r\n");
      out.write("    /* customizer */\r\n");
      out.write("    jQuery(\"#effect\").on(\"change\",function(){\r\n");
      out.write("        var x = $(this).val();\r\n");
      out.write("        jQuery(\"#thumbGrid\").data(\"nav_effect\", x);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    jQuery(\"#delay\").on(\"change\",function(){\r\n");
      out.write("        var x = parseFloat($(this).val());\r\n");
      out.write("        jQuery(\"#thumbGrid\").data(\"nav_delay\", x);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    jQuery(\"#timing\").on(\"change\",function(){\r\n");
      out.write("        var x = parseFloat($(this).val());\r\n");
      out.write("        jQuery(\"#thumbGrid\").data(\"nav_timing\", x);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    if(jQuery.isMobile){\r\n");
      out.write("        jQuery(\"body\").css({marginBottom: 140})\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- /js for recent pics section -->\r\n");
      out.write("<!-- js for testimonials -->\r\n");
      out.write("<script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // You can also use \"$(window).load(function() {\"\r\n");
      out.write("    $(function () {\r\n");
      out.write("\r\n");
      out.write("      // Slideshow 1\r\n");
      out.write("      $(\"#slider1\").responsiveSlides({\r\n");
      out.write("        maxwidth: 800,\r\n");
      out.write("        speed: 800\r\n");
      out.write("      });\r\n");
      out.write("\t});  \r\n");
      out.write("</script>\r\n");
      out.write("<!-- /js for testimonials -->\r\n");
      out.write("<!-- js for banner section -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.ba-cond.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.slitslider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\t\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar Page = (function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar $nav = $( '#nav-dots > span' ),\r\n");
      out.write("\t\t\t\t\t\tslitslider = $( '#slider' ).slitslider( {\r\n");
      out.write("\t\t\t\t\t\t\tonBeforeChange : function( slide, pos ) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$nav.removeClass( 'nav-dot-current' );\r\n");
      out.write("\t\t\t\t\t\t\t\t$nav.eq( pos ).addClass( 'nav-dot-current' );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t} ),\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tinit = function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tinitEvents();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tinitEvents = function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$nav.each( function( i ) {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$( this ).on( 'click', function( event ) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar $dot = $( this );\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif( !slitslider.isActive() ) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$nav.removeClass( 'nav-dot-current' );\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$dot.addClass( 'nav-dot-current' );\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tslitslider.jump( i + 1 );\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t} );\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t} );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\treturn { init : init };\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t})();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tPage.init();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t/**\r\n");
      out.write("\t\t\t\t * Notes: \r\n");
      out.write("\t\t\t\t * \r\n");
      out.write("\t\t\t\t * example how to add items:\r\n");
      out.write("\t\t\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $items  = $('<div class=\"sl-slide sl-slide-color-2\" data-orientation=\"horizontal\" data-slice1-rotation=\"-5\" data-slice2-rotation=\"10\" data-slice1-scale=\"2\" data-slice2-scale=\"1\"><div class=\"sl-slide-inner bg-1\"><div class=\"sl-deco\" data-icon=\"t\"></div><h2>some text</h2><blockquote><p>bla bla</p><cite>Margi Clarke</cite></blockquote></div></div>');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// call the plugin's add method\r\n");
      out.write("\t\t\t\tss.add($items);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- /js for banner section -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
